### ISSUE TITLE
Android SDK Link is out of date

### ISSUE THREAD

**Issue by sonOfRa** [mreichelt/docker-android#1]
The current version is https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip

I think this may be related to the error I'm getting when trying to start an emulator in the container in a gitlab docker runner

"Your emulator is out of date, please update by launching Android Studio"

**Comment by mreichelt** [comment]
Hi!
I assume that you were using the `mreichelt/android:latest` tag - that one has grown *way too large* (17,3G uncompressed), which is why I needed to split them up.
As a result, you should find many smaller tags here: https://hub.docker.com/r/mreichelt/android/tags/

tl;dr: Only the `X-system` variants contain the appropriate system image - the others do not even include the emulator.

Let me know if anything is missing, and I'll add it as fast as I can! :)

**Comment by sonOfRa** [comment]
I was using the 26-system tag. It seems to work in the 28-system tag, but the 26-system tag downloads an older version of the SDK as far as I can tell

**Comment by mreichelt** [comment]
I checked both the `26-system` as well as `28-system` locally - both have the latest SDK tools `26.1.1` and the latest emulator `27.3.10`.
And the latest SDK tools you mentioned are used, as you can see here: https://github.com/mreichelt/docker-android/blob/master/minimal.Dockerfile#L4

Can you provide a short, self contained, correct example for how you get to the "Your emulator is out of date, please update by launching Android Studio" message? Maybe I can fix the problem :)

**Comment by sonOfRa** [comment]
I have a GitLab CI script that looks like this:
```yml
image: mreichelt/android:28-system
minimal:
  stage: minimal
  script:
  - apt install -qq --yes qemu-kvm
  - echo "no" | avdmanager create avd -n $EMULATOR_NAME -k "system-images;android-28;default;x86"
  - $ANDROID_HOME/emulator/emulator -avd $EMULATOR_NAME -no-window -no-audio &
  - echo $! > pidfile
  - ./wait-for-emulator.sh
  after_script:
  - |
    if [ -f pidfile ]; then
      pkill -F pidfile || true
      rm -f pidfile
    fi
```

The output is here: https://gist.github.com/sonOfRa/92b8d55dfc6000c499404adede9f2a8f
Interestingly I can't recreate the old behaviour; now it still complains that the emulator is out of date, but it actually successfully starts the emulator (and in non-minimal examples, also runs the tests)
